# Generated by Django 5.1.6 on 2025-06-01 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userprofile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('prfile_image', models.ImageField(blank=True, default='images/no_image.png', upload_to='profile_images')),
                ('contact_number', models.CharField(blank=True, max_length=13)),
                ('bio', models.TextField()),
            ],
        ),
    ]
