# Generated by Django 5.1.6 on 2025-06-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='prfile_image',
            new_name='profile_image',
        ),
    ]
