# Generated by Django 5.1.6 on 2025-03-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='perticipant',
            name='event_realtion',
            field=models.ManyToManyField(to='events.event'),
        ),
    ]
