# Generated by Django 5.1.6 on 2025-03-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_perticipant_event_realtion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perticipant',
            name='event_realtion',
        ),
        migrations.AddField(
            model_name='event',
            name='event_realtion',
            field=models.ManyToManyField(to='events.event'),
        ),
    ]
