# Generated by Django 5.1.4 on 2025-04-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rsvp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='status',
        ),
    ]
