# Generated by Django 5.1.4 on 2025-04-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='static/images/no_image.png', null=True, upload_to='event_asset'),
        ),
    ]
